model:
  birads_classifier:
    model_name: 'resnet50'  # Add model architecture
    input_size: [224, 224]
    num_classes: 4
    pretrained: true
    learning_rate: 0.001
    batch_size: 32
    epochs: 500
    optimizer: Adam
    loss_function: CrossEntropyLoss

  lesion_classifier:
    model_name: 'resnet50'
    input_size: [224, 224]
    num_classes: 3
    pretrained: true
    learning_rate: 0.001
    batch_size: 32
    epochs: 500
    optimizer: Adam
    loss_function: BinaryCrossEntropyLoss

data:
  metadata_path: '/projects/OsteoLab/Tommy/BreastCancer/Code/M2net_submodel/data/metadata.csv' # "/content/M2net_submodel/data/metadata.csv"
  image_dir:  '/projects/OsteoLab/Tommy/BreastCancer/SAIGONMEC/Submodels/' # "/content"
  augmentation:
    resize: [224, 224]
    horizontal_flip: true
    vertical_flip: false
    rotation_range: 10
    zoom_range: 0.00
    brightness_range: [1.0, 1.0]

training:
  validation_split: 0.2
  shuffle: true
  seed: 42
  
output:
  base_dir: "/projects/OsteoLab/Tommy/BreastCancer/SAIGONMEC/Submodels/outputs" # "/content/outputs"
  model_dir: "models"
  log_dir: "logs"
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - kappa
  save_best_only: true
  early_stopping:
    patience: 10
    min_delta: 0.001