model:
  birads_classifier:
    model_name: 'resnet50'  # Add model architecture
    input_size: [224, 224]
    num_classes: 4
    pretrained: true
    learning_rate: 0.001
    batch_size: 32
    epochs: 50
    optimizer: Adam
    loss_function: CrossEntropyLoss

  lesion_classifier:
    input_size: [224, 224]
    num_classes: 3
    learning_rate: 0.001
    batch_size: 32
    epochs: 50
    optimizer: Adam
    loss_function: BinaryCrossEntropyLoss

data:
  metadata_path: "/content/M2net_submodel/data/metadata.csv"
  image_dir: "/content"
  augmentation:
    horizontal_flip: true
    vertical_flip: false
    rotation_range: 15
    zoom_range: 0.1
    brightness_range: [0.8, 1.2]

training:
  validation_split: 0.2
  shuffle: true
  seed: 42